### ISSUE TITLE
./hydrometer.py -c prints HTML code

### ISSUE THREAD

**Issue by bfontaine** [asparagui/homebrew-hydrometer#1]
Hi there,

Running the latest code (8dadb53), `./hydrometer.py -c` gives me HTML code instead of a clean output. Here are the first lines:

```
$ ./hydrometer.py -c
Building a list of files to process, this may take some time...





/usr/local/Library/Formula/abyss.rb:    url "https://googletest.googlecode.com/files/gtest-1.7.0.zip"



<tr class="ifOpened" onmouseout="_rowRolloverOff(this); cancelBubble=false" onmouseover="_rowRolloverOn(this)">
<td class="vt" nowrap="nowrap">
<a href="//googletest.googlecode.com/files/gtest-1.7.0.zip" onclick="_gaq.push(['siteTracker._trackEvent', 'Download - Downloaded', '//googletest.googlecode.com/files/gtest-1.7.0.zip', 'Type-Archive, OpSys-All, Featured']);_gaq.push(['projectTracker._trackEvent', 'Download - Downloaded', '//googletest.googlecode.com/files/gtest-1.7.0.zip', 'Type-Archive, OpSys-All, Featured']);" title="Download">
<img alt="Download" src="http://www.gstatic.com/codesite/ph/images/dl_arrow.gif"/>
</a>
</td>
<td class="vt id col_0">
<a href="detail?name=gtest-1.7.0.zip&amp;can=2&amp;q=">

 gtest-1.7.0.zip


</a>
</td>
<td class="vt col_1" onclick="if (!cancelBubble) _go('detail?name=gtest-1.7.0.zip&amp;can=2&amp;q=')" width="100%"><a href="detail?name=gtest-1.7.0.zip&amp;can=2&amp;q=" onclick="cancelBubble=true;">

 Source release 1.7.0


</a>

(…)
```

If that’s relevant, I’m using BeautifulSoup 4.3.2:

```
$ python3
Python 3.4.2 (default, Oct 16 2014, 05:21:12)
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.51)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import bs4
>>> bs4.__version__
'4.3.2'
```

Also FYI I’m working on a similar tool but written in Ruby, which allows me to use Homebrew’s API, called [`brew-checkupdates`](https://github.com/bfontaine/homebrew-tools/blob/master/cmd/brew-checkupdates.rb). It’s not perfect and doesn’t handle as many sources as you (only GitHub/GNU FTP for now) :smiley:

**Comment by asparagui** [comment]
@bfontaine That's what the googlecode parser has looked like for a while.  I would suggest you not spend the time dealing with GC (~150 packages, declining), as the open-source community has largely embraced Github (~750 packages, increasing) over the past few years.  Sourceforge still has a lot of packages (~600 stable) and the gnu-ftp system is very logically laid out so you should be able to write an easy parser for either.

Sorry I haven't been working on this/hb much as of late, work has been eating up most of my free time.  If you'd like any help/suggestions with your code, please feel free to message me.

**Comment by bfontaine** [comment]
Yes, IIRC Google Code doesn’t accept new tarballs anymore.

> Sorry I haven't been working on this/hb much as of late, work has been eating up most of my free time.

Don’t worry, we all have a life outside of GitHub/Homebrew :smile: 
I’ll ping you if I have any question, for now I’ll just check your code to see what I can include in my tool.
